import Head from 'next/head'
import { useDispatch, useSelector } from 'react-redux'
import Header from '@component/components/Header'
import Personal from '@component/components/Form/Personal'
import Business from '@component/components/Form/Business'
import SuccessMessage from '@component/components/Form/SuccessMessage'
import {
  RegisterState,
  selectRegister,
  setRegisterState,
} from '@component/store/registerSlice'
import styles from '@component/styles/Home.module.css'
import Form from '@component/components/Form'
import { create } from '@component/services'

const StepsManage = [Personal, Business, SuccessMessage]

const Home = () => {
  const dispatch = useDispatch()
  const registerState = useSelector(selectRegister)

  const saveRegister = (data: RegisterState) => {
    dispatch(setRegisterState(data))
  }

  const sendForm = async (data: RegisterState, file: File) => {
    return await create(data, file)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <Form
          saveRegister={saveRegister}
          sendForm={sendForm}
          state={registerState}
        />
      </main>
    </>
  )
}

export default Home
